// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vetmoxsmkyxujltgrxdc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZldG1veHNta3l4dWpsdGdyeGRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NjE2NjQsImV4cCI6MjA2MDIzNzY2NH0.hd2ipQu9Zj-z8QsOxAu2QS6PHkr-6THdhbkZYgdM7GE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);